name: Action Testing
on: [push]

jobs:
  test:
    if: contains(github.ref, 'refs/tags/') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Action
        uses: ./
        with:
          content: ./test-content
          discord-token: ${{ secrets.DISCORD_TOKEN }}
